/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/city-chat`; params?: Router.UnknownInputParams; } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/here` | `/here`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hot` | `/hot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `/event/create`; params?: Router.UnknownInputParams; } | { pathname: `/dm/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/city-chat`; params?: Router.UnknownOutputParams; } | { pathname: `/debug`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/here` | `/here`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hot` | `/hot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `/event/create`; params?: Router.UnknownOutputParams; } | { pathname: `/dm/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/event/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/city-chat${`?${string}` | `#${string}` | ''}` | `/debug${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cities${`?${string}` | `#${string}` | ''}` | `/cities${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/here${`?${string}` | `#${string}` | ''}` | `/here${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hot${`?${string}` | `#${string}` | ''}` | `/hot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/me${`?${string}` | `#${string}` | ''}` | `/me${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `/event/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/city-chat`; params?: Router.UnknownInputParams; } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cities` | `/cities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/here` | `/here`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hot` | `/hot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/me` | `/me`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `/event/create`; params?: Router.UnknownInputParams; } | `/dm/${Router.SingleRoutePart<T>}` | `/event/${Router.SingleRoutePart<T>}` | `/user/${Router.SingleRoutePart<T>}` | { pathname: `/dm/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
